# permissions for end users to edit policytypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policytype-editor-role
rules:
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policytypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policytypes/status
  verbs:
  - get
