# permissions for end users to view policytypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policytype-viewer-role
rules:
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policytypes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policytypes/status
  verbs:
  - get
