# This kustomization.yaml is not intended to be run by itself,
# since this type should not be installed on a cluster by itself.
resources:
- bases/policy.open-cluster-management.io_policytypes.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
